alarm_keywords: "\u26A0,ALARM,alarm,level,sensor,FAIL"
daily_job_done: 0
infeed:
  auto_start_level: 75
  filling_time: 300
  manual_vol_L: 100.0
  min_level_kg: 100.0
outfeed:
  draining_time: 300
  manual_vol_L: 65.0
product: SN.C&C
product_code: '5'
serial:
  baudrate: 1200
  diff: 3
  port: /dev/ttyUSB0
tank:
  density_kgl: 1.0
  hi_level_kg: 101.0
  hi_threshold_pct: 85.0
  infeed_valve: 1.0
  lo_level_kg: 60.0
  lo_threshold_pct: 20.0
  max_kg: 100.0
  tare_kg: 0.0
