import smtplib
from email.message import EmailMessage
import os
import glob
import csv
import logging
import time
from logging.handlers import TimedRotatingFileHandler

MAX_EMAIL_RETRIES = 3
EMAIL_RETRY_DELAY_SECONDS = 5

LOG_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "logs", "email")
os.makedirs(LOG_DIR, exist_ok=True)

logger = logging.getLogger("emailsend")
logger.setLevel(logging.INFO)
logger.propagate = False

if not logger.handlers:
    log_handler = TimedRotatingFileHandler(
        os.path.join(LOG_DIR, "emailsend.log"),
        when="midnight",
        interval=1,
        backupCount=29,
        encoding="utf-8",
    )
    log_handler.setFormatter(logging.Formatter(
        "%(asctime)s [%(levelname)s] %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    ))
    logger.addHandler(log_handler)


def calculate_stats(csv_path):
    in_weights = []
    out_weights = []

    with open(csv_path, newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            try:
                now_w = float(row["now_weight"])
                final_w = float(row["final_weight"])
                diff = abs(final_w - now_w)

                if now_w > final_w:
                    # OUT: weight decreased (sprayer dispensed)
                    out_weights.append(diff)
                else:
                    # IN: weight increased (tank filled)
                    in_weights.append(diff)
            except (ValueError, KeyError):
                continue

    total_records = len(in_weights) + len(out_weights)
    total_in = sum(in_weights)
    total_out = sum(out_weights)
    avg_in = total_in / len(in_weights) if in_weights else 0
    avg_out = total_out / len(out_weights) if out_weights else 0

    return {
        "total_records": total_records,
        "in_count": len(in_weights),
        "out_count": len(out_weights),
        "total_in": total_in,
        "total_out": total_out,
        "avg_in": avg_in,
        "avg_out": avg_out,
    }


def build_body(csv_path):
    filename = os.path.basename(csv_path)
    stats = calculate_stats(csv_path)

    body = f"""Hi,

This report is auto-generated by Raspberry Pi 5.
For old log files, please contact your admin.

--------------------------------------------------
  DAILY PRODUCTION SUMMARY
  File: {filename}
--------------------------------------------------

  Total Records   : {stats['total_records']}

  IN  Transactions: {stats['in_count']}
  OUT Transactions: {stats['out_count']}

  Total IN        : {stats['total_in']:.2f} kg
  Total OUT       : {stats['total_out']:.2f} kg

  Avg IN          : {stats['avg_in']:.2f} kg
  Avg OUT         : {stats['avg_out']:.2f} kg

--------------------------------------------------

Have a nice day!

Regards,
RPI5
"""
    return body


def get_latest_csv(log_dir):

    files = glob.glob(os.path.join(log_dir, "*.csv"))

    if not files:
        return None

    latest_file = max(files, key=os.path.getmtime)

    return latest_file


def send_email(subject, body, to_email, attachment_path=None):
    sender_email = "sprayer01weighingpo@gmail.com"
    sender_password = "kqwalbufyepwfnpt"

    for attempt in range(1, MAX_EMAIL_RETRIES + 1):
        stage = "message preparation"
        logger.info(
            "Email send started (attempt %s/%s): recipient=%s subject=%r attachment=%s",
            attempt,
            MAX_EMAIL_RETRIES,
            to_email,
            subject,
            os.path.basename(attachment_path) if attachment_path else "none",
        )

        try:
            msg = EmailMessage()
            msg["Subject"] = subject
            msg["From"] = sender_email
            msg["To"] = to_email
            msg.set_content(body)

            if attachment_path:
                if os.path.isfile(attachment_path):
                    with open(attachment_path, "rb") as f:
                        file_data = f.read()
                    msg.add_attachment(
                        file_data,
                        maintype="application",
                        subtype="octet-stream",
                        filename=os.path.basename(attachment_path),
                    )
                    logger.info("Attached file: %s", os.path.basename(attachment_path))
                else:
                    logger.warning("Attachment not found; sending without it: %s", attachment_path)

            stage = "SMTP connection"
            with smtplib.SMTP("smtp.gmail.com", 587, timeout=30) as smtp:
                stage = "TLS negotiation"
                smtp.starttls()

                stage = "SMTP authentication"
                smtp.login(sender_email, sender_password)

                stage = "message submission"
                refused_recipients = smtp.send_message(msg)
                if refused_recipients:
                    raise smtplib.SMTPRecipientsRefused(refused_recipients)

            logger.info("Email sent successfully: recipient=%s subject=%r", to_email, subject)
            print("Email sent successfully")
            return
        except Exception:
            logger.exception(
                "Email send failed during %s: recipient=%s subject=%r (attempt %s/%s)",
                stage,
                to_email,
                subject,
                attempt,
                MAX_EMAIL_RETRIES,
            )
            if attempt == MAX_EMAIL_RETRIES:
                raise
            logger.warning(
                "Retrying email send in %s seconds: recipient=%s subject=%r",
                EMAIL_RETRY_DELAY_SECONDS,
                to_email,
                subject,
            )
            time.sleep(EMAIL_RETRY_DELAY_SECONDS)



#send_email("PLANT_01_PALM_OLEIN_SPRAYER","Hi\nThis is generated by rasbperryPi 5. for the old log files, Please contact your admin.\nHave a nice day!!!\n\nThank you.\n\nRegard\nRPI5 ","sprayer01weighingpo@malibangroup.lk",get_latest_csv("/home/palmoil/stuff/logs"))